---
name: Deploy Website
on:
  push:
    branches: [ pn-storybook-poc ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Ember Build
        run: |
          yarn && ember build
      - name: Webpack assets workaround fix
        run: |
          cp -R .storybook/oss/images .storybook/oss/less/layouts/
          cp -R .storybook/oss/fonts .storybook/oss/less/core/
      - name: Storybook Build
        run: yarn build-storybook
      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./storybook-static/
          cname:  storybook.upfluence.co
